import PDFDocument from "pdfkit";
import type { ProjectDetails } from "./submission-service.js";
import type { ComplianceViolation, ModuleResult } from "./compliance-guardian.js";
import type { BrandingConfig } from "../lib/branding-store.js";

const DEFAULT_BRAND_COLOR = "#1a365d";
const DEFAULT_ACCENT_COLOR = "#2b6cb0";
const ERROR_COLOR = "#c53030";
const WARNING_COLOR = "#c05621";
const INFO_COLOR = "#2b6cb0";
const SUCCESS_COLOR = "#276749";

function resolveBrand(branding?: BrandingConfig): { brandColor: string; accentColor: string } {
  const primary = branding?.primaryColor ?? DEFAULT_BRAND_COLOR;
  return { brandColor: primary, accentColor: DEFAULT_ACCENT_COLOR };
}

function drawHeader(
  doc: typeof PDFDocument.prototype,
  title: string,
  subtitle?: string,
  branding?: BrandingConfig,
): void {
  const { brandColor } = resolveBrand(branding);
  const companyName = branding?.companyName ?? "OpenMEP";
  const companyTagline = "Engineering Submission System";

  doc.rect(0, 0, doc.page.width, 70).fill(brandColor);

  if (branding?.logoBase64) {
    try {
      const logoBuffer = Buffer.from(branding.logoBase64, "base64");
      doc.image(logoBuffer, doc.page.width - 90, 10, { height: 50, fit: [80, 50] });
    } catch {
    }
  }

  doc.fillColor("white").fontSize(20).font("Helvetica-Bold").text(companyName, 40, 18);
  doc.fontSize(9).font("Helvetica").text(companyTagline, 40, 42);

  const titleX = 200;
  const titleW = branding?.logoBase64 ? doc.page.width - 300 : doc.page.width - 240;

  doc.fontSize(14).font("Helvetica-Bold").text(title, titleX, 22, {
    align: "right",
    width: titleW,
  });

  if (subtitle) {
    doc.fontSize(9).font("Helvetica").text(subtitle, titleX, 42, {
      align: "right",
      width: titleW,
    });
  }

  doc.fillColor(brandColor);
  doc.rect(40, 80, doc.page.width - 80, 1).fill(DEFAULT_ACCENT_COLOR);
  doc.moveDown(0.5);
}

function drawFooter(doc: typeof PDFDocument.prototype, branding?: BrandingConfig): void {
  const bottom = doc.page.height - 40;
  const footerText = branding?.footerText ?? "Generated by OpenMEP Submission Packager";

  doc.fillColor("#718096").fontSize(8).font("Helvetica");
  doc.rect(40, bottom - 8, doc.page.width - 80, 0.5).fill("#e2e8f0");
  doc.fillColor("#718096").text(footerText, 40, bottom, { align: "left" });
  doc.text(new Date().toISOString().split("T")[0]!, 40, bottom, {
    align: "right",
    width: doc.page.width - 80,
  });
}

function drawSectionHeading(
  doc: typeof PDFDocument.prototype,
  text: string,
  branding?: BrandingConfig,
): void {
  const { brandColor } = resolveBrand(branding);
  doc.moveDown(0.8);
  doc.fillColor(brandColor).fontSize(12).font("Helvetica-Bold").text(text);
  doc.rect(doc.x, doc.y + 2, doc.page.width - 80, 1).fill(DEFAULT_ACCENT_COLOR);
  doc.fillColor("#2d3748");
  doc.moveDown(0.5);
}

function drawKeyValue(
  doc: typeof PDFDocument.prototype,
  label: string,
  value: string,
): void {
  const labelWidth = 150;
  const x = doc.x;
  const y = doc.y;
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#4a5568").text(label, x, y, {
    width: labelWidth,
    continued: false,
  });
  doc.fontSize(9).font("Helvetica").fillColor("#1a202c").text(value, x + labelWidth, y, {
    width: doc.page.width - 80 - labelWidth,
  });
}

function drawSignOffBlock(
  doc: typeof PDFDocument.prototype,
  engineerName: string,
  engineerLicense?: string,
  submissionDate?: string,
  branding?: BrandingConfig,
): void {
  doc.moveDown(2);
  doc.fillColor("#2d3748").fontSize(10).font("Helvetica-Bold").text("Signature:");
  doc.moveDown(0.5);

  if (branding?.stampBase64) {
    try {
      const stampBuffer = Buffer.from(branding.stampBase64, "base64");
      doc.image(stampBuffer, doc.x, doc.y, { height: 60, fit: [120, 60] });
      doc.moveDown(4);
    } catch {
      doc.rect(doc.x, doc.y, 200, 1).fill("#4a5568");
      doc.moveDown(0.5);
    }
  } else {
    doc.rect(doc.x, doc.y, 200, 1).fill("#4a5568");
    doc.moveDown(0.5);
  }

  doc.fontSize(9).font("Helvetica").fillColor("#718096").text(
    `${engineerName}${engineerLicense ? ` — Lic. ${engineerLicense}` : ""}`,
  );
  if (submissionDate) {
    doc.text(`Date: ${submissionDate}`);
  }
}

function bufferFromDoc(doc: typeof PDFDocument.prototype): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

export async function generateCoverLetterPDF(
  details: ProjectDetails,
  violations: ComplianceViolation[],
  branding?: BrandingConfig,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40, compress: false });

  const errorCount = violations.filter((v) => v.severity === "error").length;
  const warningCount = violations.filter((v) => v.severity === "warning").length;
  const isCompliant = errorCount === 0;

  drawHeader(doc, "SUBMISSION COVER LETTER", details.projectNumber, branding);

  doc.moveDown(1.2);
  doc.y = 100;

  drawSectionHeading(doc, "PROJECT INFORMATION", branding);
  drawKeyValue(doc, "Project Name:", details.projectName);
  drawKeyValue(doc, "Project Number:", details.projectNumber);
  drawKeyValue(doc, "Client:", details.clientName);
  drawKeyValue(doc, "Submission Date:", details.submissionDate);
  drawKeyValue(doc, "Revision:", details.revisionNumber);

  drawSectionHeading(doc, "ENGINEER DETAILS", branding);
  drawKeyValue(doc, "Engineer:", branding?.engineerName ?? details.engineerName);
  const licNo = branding?.licenceNumber ?? details.engineerLicense;
  if (licNo) {
    drawKeyValue(doc, "License No.:", licNo);
  }
  drawKeyValue(doc, "Company:", branding?.companyName ?? details.companyName);

  drawSectionHeading(doc, "COMPLIANCE SUMMARY", branding);

  const statusColor = isCompliant ? SUCCESS_COLOR : ERROR_COLOR;
  const statusText = isCompliant
    ? `✓  COMPLIANT — All checks passed`
    : `✗  NON-COMPLIANT — ${errorCount} error(s), ${warningCount} warning(s)`;

  doc.rect(doc.x, doc.y, doc.page.width - 80, 28).fill(isCompliant ? "#f0fff4" : "#fff5f5");
  doc.fillColor(statusColor).fontSize(11).font("Helvetica-Bold").text(
    statusText,
    doc.x + 10,
    doc.y - 22,
    { width: doc.page.width - 100 },
  );
  doc.moveDown(1.2);

  doc.fillColor("#4a5568").fontSize(9).font("Helvetica");
  drawKeyValue(doc, "Errors:", String(errorCount));
  drawKeyValue(doc, "Warnings:", String(warningCount));
  drawKeyValue(doc, "Infos:", String(violations.filter((v) => v.severity === "info").length));

  if (details.notes) {
    drawSectionHeading(doc, "NOTES", branding);
    doc.fillColor("#2d3748").fontSize(10).font("Helvetica").text(details.notes, {
      width: doc.page.width - 80,
    });
  }

  drawSectionHeading(doc, "ENGINEER DECLARATION", branding);
  doc
    .fillColor("#2d3748")
    .fontSize(10)
    .font("Helvetica")
    .text(
      "I certify that the calculations contained in this submission package have been " +
        "prepared in accordance with the applicable codes and standards referenced herein, " +
        "and are correct to the best of my knowledge.",
      { width: doc.page.width - 80 },
    );

  drawSignOffBlock(
    doc,
    branding?.engineerName ?? details.engineerName,
    branding?.licenceNumber ?? details.engineerLicense,
    details.submissionDate,
    branding,
  );

  drawFooter(doc, branding);

  return bufferFromDoc(doc);
}

export async function generateComplianceMatrixPDF(
  moduleResults: ModuleResult[],
  violations: ComplianceViolation[],
  branding?: BrandingConfig,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40, compress: false });

  drawHeader(doc, "COMPLIANCE MATRIX", "Cross-Module Compliance Report", branding);

  doc.y = 100;

  drawSectionHeading(doc, "MODULES CHECKED", branding);
  doc.fillColor("#2d3748").fontSize(10).font("Helvetica").text(
    moduleResults.map((m) => `${m.module} (${m.region})`).join(", "),
    { width: doc.page.width - 80 },
  );

  drawSectionHeading(doc, "VIOLATIONS SUMMARY", branding);

  const errorCount = violations.filter((v) => v.severity === "error").length;
  const warningCount = violations.filter((v) => v.severity === "warning").length;
  const infoCount = violations.filter((v) => v.severity === "info").length;

  drawKeyValue(doc, "Total Violations:", String(violations.length));
  drawKeyValue(doc, "Errors:", String(errorCount));
  drawKeyValue(doc, "Warnings:", String(warningCount));
  drawKeyValue(doc, "Infos:", String(infoCount));

  drawSectionHeading(doc, "VIOLATION DETAILS", branding);

  if (violations.length === 0) {
    doc.rect(doc.x, doc.y, doc.page.width - 80, 30).fill("#f0fff4");
    doc.fillColor(SUCCESS_COLOR).fontSize(11).font("Helvetica-Bold").text(
      "✓  No violations found — all checks passed.",
      doc.x + 10,
      doc.y - 24,
      { width: doc.page.width - 100 },
    );
    doc.moveDown(2);
  } else {
    for (const v of violations) {
      if (doc.y > doc.page.height - 150) {
        doc.addPage();
        drawHeader(doc, "COMPLIANCE MATRIX (cont.)", "Cross-Module Compliance Report", branding);
        doc.y = 100;
      }

      const sevColor =
        v.severity === "error"
          ? ERROR_COLOR
          : v.severity === "warning"
            ? WARNING_COLOR
            : INFO_COLOR;
      const sevBg =
        v.severity === "error"
          ? "#fff5f5"
          : v.severity === "warning"
            ? "#fffaf0"
            : "#ebf8ff";

      const boxTop = doc.y;
      doc.rect(doc.x, boxTop, doc.page.width - 80, 80).fill(sevBg);

      doc
        .fillColor(sevColor)
        .fontSize(9)
        .font("Helvetica-Bold")
        .text(`[${v.severity.toUpperCase()}]`, doc.x + 8, boxTop + 8, { width: 60 });

      doc
        .fillColor("#1a202c")
        .fontSize(9)
        .font("Helvetica-Bold")
        .text(v.module.toUpperCase(), doc.x + 70, boxTop + 8, { width: 100 });

      doc
        .fillColor("#718096")
        .fontSize(8)
        .font("Helvetica")
        .text(v.standardClause, doc.x + 180, boxTop + 8, {
          width: doc.page.width - 80 - 188,
        });

      doc
        .fillColor("#2d3748")
        .fontSize(9)
        .font("Helvetica")
        .text(v.message, doc.x + 8, boxTop + 26, { width: doc.page.width - 96 });

      doc
        .fillColor("#4a5568")
        .fontSize(8)
        .font("Helvetica")
        .text(
          `Parameter: ${v.parameter}   Actual: ${v.actualValue}${v.unit ? " " + v.unit : ""}   Limit: ${v.limit}${v.unit ? " " + v.unit : ""}`,
          doc.x + 8,
          boxTop + 58,
          { width: doc.page.width - 96 },
        );

      doc.y = boxTop + 88;
      doc.moveDown(0.3);
    }
  }

  drawFooter(doc, branding);
  return bufferFromDoc(doc);
}

export async function generateBOQSummaryPDF(
  moduleResults: ModuleResult[],
  branding?: BrandingConfig,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40, compress: false });

  drawHeader(doc, "BOQ SUMMARY", "Bill of Quantities", branding);

  doc.y = 100;

  for (const result of moduleResults) {
    if (doc.y > doc.page.height - 200) {
      doc.addPage();
      drawHeader(doc, "BOQ SUMMARY (cont.)", "Bill of Quantities", branding);
      doc.y = 100;
    }

    drawSectionHeading(doc, `${result.module.toUpperCase()} — ${result.region}`, branding);

    const params = Object.entries(result.parameters);
    for (const [key, value] of params) {
      drawKeyValue(
        doc,
        key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) + ":",
        String(value),
      );
    }
    doc.moveDown(0.5);
  }

  drawFooter(doc, branding);
  return bufferFromDoc(doc);
}

export async function generateCalculationPDF(
  result: ModuleResult,
  projectDetails: Pick<ProjectDetails, "projectName" | "projectNumber" | "submissionDate">,
  branding?: BrandingConfig,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40, compress: false });

  drawHeader(
    doc,
    `${result.module.toUpperCase()} CALCULATION`,
    `${result.region} Standard`,
    branding,
  );

  doc.y = 100;

  drawSectionHeading(doc, "CALCULATION DETAILS", branding);
  drawKeyValue(doc, "Project:", projectDetails.projectName);
  drawKeyValue(doc, "Project No.:", projectDetails.projectNumber);
  drawKeyValue(doc, "Date:", projectDetails.submissionDate);
  drawKeyValue(doc, "Module:", result.module);
  drawKeyValue(doc, "Region / Standard:", result.region);

  drawSectionHeading(doc, "INPUT PARAMETERS", branding);
  for (const [key, value] of Object.entries(result.parameters)) {
    drawKeyValue(
      doc,
      key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) + ":",
      String(value),
    );
  }

  drawFooter(doc, branding);
  return bufferFromDoc(doc);
}
