import { Readable } from "node:stream";
import JSZip from "jszip";
import {
  runComplianceCheck,
  type ModuleResult,
  type ComplianceViolation,
} from "./compliance-guardian.js";
import {
  generateCoverLetterPDF,
  generateComplianceMatrixPDF,
  generateBOQSummaryPDF,
  generateCalculationPDF,
} from "./pdf-generator.js";
import type { BrandingConfig } from "../lib/branding-store.js";

export interface ProjectDetails {
  projectName: string;
  projectNumber: string;
  clientName: string;
  engineerName: string;
  engineerLicense?: string;
  companyName: string;
  submissionDate: string;
  revisionNumber: string;
  notes?: string;
}

export interface SubmissionPackageRequest {
  projectDetails: ProjectDetails;
  moduleResults: ModuleResult[];
  includedModules?: string[];
  branding?: BrandingConfig;
}

export interface SubmissionPackageResult {
  zipBuffer: Buffer;
  zipStream: Readable;
  violations: ComplianceViolation[];
  hasErrors: boolean;
}

function generateVersionLog(details: ProjectDetails): string {
  return [
    "VERSION LOG",
    "===========",
    "",
    `Project:     ${details.projectName} (${details.projectNumber})`,
    `Revision:    ${details.revisionNumber}`,
    `Date:        ${details.submissionDate}`,
    `Prepared by: ${details.engineerName}, ${details.companyName}`,
    "",
    "─────────────────────────────────────",
    "Rev  | Date              | Description",
    "─────────────────────────────────────",
    `${details.revisionNumber.padEnd(4)} | ${details.submissionDate.padEnd(17)} | Initial submission`,
    "",
    "Generated by OpenMEP Submission Packager",
  ].join("\n");
}

export async function buildSubmissionPackage(
  request: SubmissionPackageRequest,
): Promise<SubmissionPackageResult> {
  const { projectDetails, moduleResults, includedModules, branding } = request;

  const filteredModules =
    includedModules && includedModules.length > 0
      ? moduleResults.filter((m) => includedModules.includes(m.module))
      : moduleResults;

  const violations = runComplianceCheck(filteredModules);
  const hasErrors = violations.some((v) => v.severity === "error");

  const zip = new JSZip();

  const coverLetterPDF = await generateCoverLetterPDF(projectDetails, violations, branding);
  zip.file("cover_letter.pdf", coverLetterPDF);

  const complianceMatrixPDF = await generateComplianceMatrixPDF(filteredModules, violations, branding);
  zip.file("compliance_matrix.pdf", complianceMatrixPDF);

  const boqSummaryPDF = await generateBOQSummaryPDF(filteredModules, branding);
  zip.file("boq_summary.pdf", boqSummaryPDF);

  zip.file("version_log.txt", generateVersionLog(projectDetails));

  zip.file(
    "compliance_violations.json",
    JSON.stringify(violations, null, 2),
  );

  const calcsFolder = zip.folder("calculations");
  if (calcsFolder) {
    for (const result of filteredModules) {
      const calcPDF = await generateCalculationPDF(
        result,
        {
          projectName: projectDetails.projectName,
          projectNumber: projectDetails.projectNumber,
          submissionDate: projectDetails.submissionDate,
        },
        branding,
      );
      calcsFolder.file(
        `${result.module}_${result.region}_calculation.pdf`,
        calcPDF,
      );
    }
  }

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
  const zipStream = Readable.from(zipBuffer);

  return {
    zipBuffer,
    zipStream,
    violations,
    hasErrors,
  };
}
